# Generated by Django 5.1.3 on 2024-11-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='purchases',
            field=models.ManyToManyField(blank=True, related_name='buyers', to='backend1.product'),
        ),
    ]
